apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  containers:
  - image: selaworkshops/echoserver:1.4
    name: echoserver
    ports:
    - containerPort: 8080

    
