apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  labels:
    app: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        name: php-apache
        resources:
          requests:
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
spec:
  ports:
  - name: php-apache
    port: 80
  selector:
    app: php-apache
    
